/***************************************************************************
 *   Copyright (C) 2009 by Adam Goossens                                   *
 *   adam@kmess.org                                                        *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Lesser General Public License as        *
 *   published by the Free Software Foundation; either version 2.1 of the  *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU Lesser General Public      *
 *   License along with this program; if not, write to the                 *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

#ifndef ISFDRAWING_H
#define ISFDRAWING_H

// FORWARD DECLARATIONS
class QByteArray;

namespace Isf
{

/**
 * A list of all known ISF tag indexes into the GUID
 * table.
 */
enum IsfTags
{
  TAG_INK_SPACE_RECT = 0,
  TAG_GUID_TABLE,
  TAG_DRAW_ATTRS_TABLE,
  TAG_DRAW_ATTRS_BLOCK
};

/**
 * Possible errors generated by the ISF parser.
 */
enum IsfParserError
{
  ISF_ERROR_NONE = 0,         // no error.
  ISF_ERROR_BAD_VERSION,      // incompatible ISF version
  ISF_ERROR_BAD_STREAMSIZE    // streamsize of ISF data is too small.
};

/**
 * ISF parser state machine states.
 */
enum IsfParserState
{
  ISF_PARSER_START = 0,
  ISF_PARSER_FINISH,
  ISF_PARSER_VERSION,
  ISF_PARSER_STREAMSIZE,
  ISF_PARSER_TAG
};


/**
 * This class loads ISF (Ink Serialized Format) drawings.
 *
 * @author Adam Goossens (adam@kmess.org)
 */
class IsfDrawing
{
  public:
    static const unsigned short SUPPORTED_ISF_VERSION = 0;

    /***** CONSTRUCTORS ****/
  public:
    IsfDrawing();

    /***** PUBLIC METHODS ****/
  public:
    // true if this is a null IsfDocument, false otherwise.
    bool                 isNull() const;
    // last parser error.
    IsfParserError       parserError() const;

    
    /**** STATIC METHODS ****/
  public:
    // builds an ISF drawing object from raw ISF data.
    static IsfDrawing      fromIsfData(const QByteArray &data);

    /***** MEMBER VARIABLES ****/
  private:
    // is this a null document?
    bool            isNull_;
    // parser error (if there is one)
    IsfParserError  parserError_;

};

}

#endif // ISFDRAWING_H
