/***************************************************************************
 *   Copyright (C) 2008 by Valerio Pilo                                    *
 *   valerio@kmess.org                                                     *
 *                                                                         *
 *   Copyright (C) 2009 by Adam Goossens                                   *
 *   adam@kmess.org                                                        *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Lesser General Public License as        *
 *   published by the Free Software Foundation; either version 2.1 of the  *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU Lesser General Public      *
 *   License along with this program; if not, write to the                 *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

#ifndef LIBISFTYPES_H
#define LIBISFTYPES_H

#include <QList>
#include <QRectF>
#include <QPointF>
#include <QSizeF>
#include <QtGlobal>


/**
 * Uncomment this define to enable debugging output
 */
#define ISF_DEBUG_VERBOSE



namespace Isf
{



  /**
   * A list of all known ISF tag indexes into the GUID
   * table
   */
  enum DataTags
  {
    TAG_INK_SPACE_RECT                  = 0
  , TAG_GUID_TABLE
  , TAG_DRAW_ATTRS_TABLE
  , TAG_DRAW_ATTRS_BLOCK
  , TAG_STROKE_DESC_TABLE
  , TAG_STROKE_DESC_BLOCK
  , TAG_BUTTONS
  , TAG_NO_X
  , TAG_NO_Y
  , TAG_DIDX
  , TAG_STROKE
  , TAG_STROKE_PROPERTY_LIST
  , TAG_POINT_PROPERTY
  , TAG_SIDX
  , TAG_COMPRESSION_HEADER
  , TAG_TRANSFORM_TABLE
  , TAG_TRANSFORM
  , TAG_TRANSFORM_ISOTROPIC_SCALE
  , TAG_TRANSFORM_ANISOTROPIC_SCALE
  , TAG_TRANSFORM_ROTATE
  , TAG_TRANSFORM_TRANSLATE
  , TAG_TRANSFORM_SCALE_AND_TRANSLATE
  , TAG_TRANSFORM_QUAD
  , TAG_TIDX
  , TAG_METRIC_TABLE
  , TAG_METRIC_BLOCK
  , TAG_MIDX
  , TAG_MANTISSA
  , TAG_PERSISTENT_FORMAT
  , TAG_HIMETRIC_SIZE
  , TAG_STROKE_IDS
  };



  /**
   * Possible errors generated by the ISF parser
   */
  enum IsfError
  {
    ISF_ERROR_NONE = 0           /// no error
  , ISF_ERROR_BAD_VERSION        /// incompatible ISF version
  , ISF_ERROR_BAD_STREAMSIZE     /// stream size of ISF data is too small
  };



  /**
   * Stroke drawing flags
   */
  enum StrokeFlag
  {
    FitToCurve     = 0x0001
  , IgnorePressure = 0x0004
  , IsHighlighter  = 0x0100
  , IsRectangle    = 0x0200
  };
  Q_DECLARE_FLAGS( StrokeFlags, StrokeFlag )
  Q_DECLARE_OPERATORS_FOR_FLAGS( StrokeFlags )



  /**
   * Drawing attributes for points
   */
  struct PointAttributes
  {
    /// dimensions of the pencil in Himetric units
    QSizeF penSize;
    /// color in AABBGGRR format (Alpha channel: 00 is solid, FF is transparent)
    quint32 color;
    /// mask of StrokeFlags
    StrokeFlags flags;
    /// number of strokes using those attributes
    quint32 nStrokes;
  };



  /**
   * A single point within a stroke
   */
  struct Point
  {
    /// coordinates
    QPointF position;
    /// Pressure information
    qint64  pressureLevel;
    /// Drawing attributes structure used to display the stroke
    PointAttributes drawAttrs;
  };



  /**
   * A pen stroke
   */
  struct Stroke
  {
    /// List of points contained in this stroke
    QList<Point> points;
    /// Its bounding box, ie the minimum sized rectangle which contains all of the stroke's points
    QRectF boundingBox;
  };



  /**
   * A complete ISF image
   */
  struct Image
  {
    /// Bounding box, the minimum sized rectangle which contains all the strokes
    QRectF boundingBox;
    /// Dimensions of the image, or of the area used to draw the ISF
    QSize size;
    /// highest pencil dimension used
    QSizeF maxPenSize;

    /// collection of strokes
    QList<Stroke> strokes;
  };



}



#endif
